name: Create Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'k8s/**'
      - 'docs/**'
  
  # Allow manual triggers for testing
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    # Don't run on commits that only update workflows, docs, etc.
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Use semantic-release for automated versioning
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
        
      # Create release configuration
      - name: Create .releaserc
        run: |
          cat > .releaserc << 'EOF'
          {
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              ["@semantic-release/npm", {
                "npmPublish": false
              }],
              ["@semantic-release/exec", {
                "prepareCmd": "echo 'New version: ${nextRelease.version}'"
              }],
              ["@semantic-release/git", {
                "assets": ["package.json", "CHANGELOG.md"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }],
              "@semantic-release/github"
            ]
          }
          EOF
          
      # Manual version bump if running from workflow_dispatch
      - name: Bump version manually
        if: github.event_name == 'workflow_dispatch'
        run: |
          BUMP="${{ github.event.inputs.bump }}"
          npm --no-git-tag-version version $BUMP
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "chore(release): bump version to $VERSION [skip ci]"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push --follow-tags
          echo "Tagged v$VERSION"
      
      # Automatic versioning using semantic-release (when not manually triggered)
      - name: Create release
        if: github.event_name != 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 